name: Future Webpage - Test

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        cd future_webpage
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test + Flake + PEP8 + Coverage
      run: |
        cd future_webpage
        export DJANGO_SETTINGS_MODULE="dgf_cms.settings"
        pytest --cov=dgf --cov-config=.coveragerc --ignore=env  --flakes --pep8
      env:
        DJANGO_ENV: test
